### ISSUE TITLE
Prototype 7 crashes extracting Metroid Prime 1 ISO

### ISSUE THREAD

**Issue by athairus** [AxioDL/urde#12]
The first time I ran extract on my Prime 1 ISO (1.0 NTSC, CRC32:`852B658C`) it finished completely. The first time I extracted I was to my user folder (`C:\Users\athairus`) and extracted there just fine. 

I had noticed the program left shortcut files instead of symlinks so I decided that moving the files to a better location was not feasable. Instead, I just ran the command in a different folder. It always crashes now with the message: `[x.xxxx FATAL ERROR BlenderConnection] Invalid argument`. It doesn't crash in the same place each time.

All I can say is the crash has nothing to do with spaces in the path... I wish I could provide more info but the build from the forums doesn't have any debug symbols.

Here's a raw pastebin with several attempts. The first attempt failed because I had to install Blender, the next attempt was the only successful one.

http://pastebin.com/yaBzRvP9

Blender 2.76b
Windows 10 x64

**Comment by jackoalan** [comment]
Thanks for the report!

We've gone back and forth on using symlinks (or shell-links for windows). It makes the project directory much less portable (despite our efforts to use relative paths).

As the project matures, we'll probably remove them in favor of a custom database with direct paths.

For now, the only short-term advice i have is to delete the project directory and start over (including the contained .hecl directory).

**Comment by Antidote** [comment]
I think the "Invalid Argument" error is an artifact from the initial failure.

**Comment by jackoalan** [comment]
I have an update on this issue.

#14 is being made to extract files while dropping Retro's original file hashes; substituting them with relative project paths. You'll see these paths in .yaml files and other intermediates extracted by hecl. Blender files are already pretty much 100% relative-path-based.

This update also does away with symlinks/shell-links once and for all; with hecl itself following paths and performing dependency resolution for repackaging operations.

**Comment by James-cB** [comment]
I'm getting a crash with both Prime 1 and 2 on making the connection to Blender, I can't even make it to the point where athairus got to. I changed versions thinking that was the problem, and the only thing that changed was the error went from Blender.exe has stopped working to hecl.exe has stopped working. https://gyazo.com/e8796497a1705e4769b454efd5e595d2

 It seems that you guys may have figured it out already, so I'll try compiling from the repo next to see if that does anything.

**Comment by Antidote** [comment]
Closing as invalid, tested and working on windows 7 and 10 with latest changes.
