### ISSUE TITLE
Blender connection issue on Windows

### ISSUE THREAD

**Issue by kraid** [AxioDL/urde#15]
i was going to try out your program, but it always failed at Establishing BlenderConnection, with a Fatal Error: unable to install blender addon using 'C'

OS: Win7 64bit (german)
Blender 2.76b (in C:\Programme\Blender Foundation\Blender)
VS redist x64 installed
Using the precompiled hecl.p6e.win7-bit.exe
Also i deleted the folders created by hecl after each fail.

I've had issues with some programms before that didn't install into "Programme" because they were looking for "Program Files" and then threw their stuff into:
C:\VTRoot\HardDiskVolume

**Comment by Antidote** [comment]
Looks like we'll need to ask windows where it is, though can you try this: 
set BLENDER_BIN="PathToBlender" and run hecl again?

**Comment by Antidote** [comment]
Jack has uploaded a new prototype, can you please test this to make sure it works properly?

**Comment by kraid** [comment]
It works.
Still at unpacking Metroid1.pak, where it got very slow at 90%, but i guess that's just normal.

**Comment by Antidote** [comment]
Yep, maps can take a bit to extract, they're the largest resources in the game.
