### ISSUE TITLE
URDE does not build on Windows since commit @43c8cdf

### ISSUE THREAD

**Issue by yonicstudios** [AxioDL/urde#20]
I've been trying to compile URDE since @43c8cdf on VS 2015 and Qt, but I think it may extend from @b9baa84.

[VS 2015 Build log](http://pastebin.com/LVGQdHip) at latest commit, from Win7 x64. EDIT: Windows 10 AU x64 reports an almost identical log.

EDIT 3: [Qt Build log](http://pastebin.com/byuN2t6z) at latest commit, from same machine, sharing error [C2665](https://msdn.microsoft.com/en-us/library/c8ft1y6y.aspx) with the previous log.

This issue may be related to #19, since errors [C2027](https://msdn.microsoft.com/en-us/library/aa229181%28v=vs.60%29.aspx) and [C2338](https://msdn.microsoft.com/en-us/library/30fssaba.aspx) which I suppose are the main errors that cause this issue, appear repeatedly in my log.

EDIT 2: @DiThi tried to build at latest commit and @a2b07ba on Kubuntu, but had [this error](http://i.imgur.com/T1dwNrp.jpg) instead.

**Comment by Antidote** [comment]
*sigh* I just _has_ to be MSVC that gives us headaches.

These errors are actually pretty frivolous so I don't know why MSVC is pinging on them, I'm working on correcting them at the moment, so the next commit _should_ build for you.

**Comment by Antidote** [comment]
The latest commit should fix the windows build, please give it a shot.

**Comment by Antidote** [comment]
Just did a fresh build on kubuntu 16.10 and it's fine on my end, definitely double check packages.

**Comment by yonicstudios** [comment]
Yeah, I think MSVC is _very_ strict when it comes to building stuff.
Anyway, now it does build, so I'm closing this.
@DiThi updated libpng-dev and installed libvulkan-dev, reported a correct build as well.
I would love to contribute making the code friendlier for MSVC, but my C++ knowledge is quite rusty. Maybe in the future I'll fork the repo and start adding a bit of stability.

**Comment by Antidote** [comment]
That's perfectly ok, @jackoalan is currently working on appveyor integration

**Comment by jackoalan** [comment]
Part of the problem for us is we build on Windows rather infrequently. I'm in the process of setting up AppVeyor to being failed builds to our attention much sooner.
