### ISSUE TITLE
MP1/Tweaks/PlayerRes.yaml fields shifted by two lines

### ISSUE THREAD

**Issue by cylgom** [AxioDL/urde#22]
I created a new Metroid Prime 1 project with "hecl extract /path/to/iso ./"
Then I tried to import it in urde, but encountered the following error:
`[588.4102 ERROR urde::ProjectResourceFactoryBase (Boo Client Thread)] MP1/GGuiSys/YButtonOut.png: expected type 'ANCS', found 'TXTR'`
`[588.4104 ERROR urde::ProjectResourceFactoryBase (Boo Client Thread)] unable to spin-build ANCS 8419F209`
We can trace the error back to "MP1/Tweaks/PlayerRes.yaml" fields, [most of which are shifted by two lines](https://pastebin.com/6YCHdBfJ). I don't know why, however :/
(Maybe the empty "case SBIG('CTWK')" at line 388 in DataSpec/DNAMP1/DNAMP1.cpp which executes the following "case SBIG('DUMB')" ?)

**Comment by Antidote** [comment]
Hmm, the string comparison should prevent that.....

**Comment by Antidote** [comment]
Hmmm, I just re-extracted PlayerRes and I have a valid YAML, do you mind providing the original stored in `.hecl/cooked/MP1-ORIG.spec`?

**Comment by cylgom** [comment]
Sure. I think this is a pal iso if that helps (it's from teh internet, I didn't want to rip it myself...)
[playerres.zip](https://github.com/AxioDL/urde/files/1066445/playerres.zip)

**Comment by Antidote** [comment]
ah ha!

![image](https://user-images.githubusercontent.com/3392773/27011329-12e39a60-4e6e-11e7-85bb-3d174e154a5f.png)

Looks like PAL removed a couple strings.

**Comment by cylgom** [comment]
I guess, considering the amount of [differences between versions](http://metroid.wikia.com/wiki/List_of_Metroid_Prime_version_differences) ^^

**Comment by Antidote** [comment]
Well, most of those changes are done via level scripting, this is deep within the bowels of the engine, doing version specific code paths is pretty trivial to implement, but fairly low priority atm, since we're concentrating on NTSC v1.088.

**Comment by cylgom** [comment]
ok, I'll get that version then

**Comment by Antidote** [comment]
It'll be listed as NTSC 0-00, however it's best to just rip your own version.

**Comment by Antidote** [comment]
hecl also reports the internal version.

**Comment by cylgom** [comment]
I live in Europe, so for now I only have access to PAL versions :/

**Comment by Antidote** [comment]
Darn, well I've done my due diligence ;P

**Comment by cylgom** [comment]
Now I can see the introduction "Unidentified distress beacon" etc. but at the end of the message nothing happens and I have the following errors: 
`[2.8664 ERROR urde::ProjectResourceFactoryBase (Boo Client Thread)] unable to find async load resource (MLVL, 24CDEE74)`
`[2.8825 INFO urde::ProjectResourceFactoryBase (Boo Client Thread)] async-built TXTR 624B6528`

**Comment by jackoalan** [comment]
That's as far as we've gotten as well. The initial MLVL id is hard-coded in the game, it could be different in the PAL version.

There's not much we can progress beyond that initial text typing until core entities are implemented (like CPlayer, probably CMorphBall, and everything Exterior Docking Hangar depends on).

**Comment by cylgom** [comment]
Ok, thank you very much for your help :)
