### ISSUE TITLE
Cannot compile urde.

### ISSUE THREAD

**Issue by slawekwaga** [AxioDL/urde#25]
I try to compile URDE. This is the compile log.
[log.txt](https://github.com/AxioDL/urde/files/1378606/log.txt)
 cmake: 3.9.3
lmms: 5.0.0
python: 3.6.2

**Comment by Antidote** [comment]
This has already been fixed locally and a commit is nearly ready to be pushed.

**Comment by Antidote** [comment]
Pushed the fix, if you have further issues compiling feel free to re-open or create a new issue
