### ISSUE TITLE
Can I disable Vulkan?

### ISSUE THREAD

**Issue by slawekwaga** [AxioDL/urde#27]
Not bug, but more like a question.
Can you disable vulkan at boo submodule from urde cmake?

**Comment by jackoalan** [comment]
There’s not currently a way to disable it via cmake (unless the vulkan runtime is uninstalled from the machine). The main reasoning for this is you’re able to disable it at runtime by passing `--gl` to urde. If there’s a problem initializing the Vulkan driver, it will automatically fall back to GL.

**Comment by slawekwaga** [comment]
Understood. Closing.
