### ISSUE TITLE
Interrupting the extraction may produce broken files.

### ISSUE THREAD

**Issue by slawekwaga** [AxioDL/urde#28]
I've encountered a problem.
If you interrupt extraction some of the files extracted or converted may not be deletable at all.
Just throw a SIGKILL (Ctrl-C in unix) and try to delete the directory, where the files are extracted.

**Comment by jackoalan** [comment]
How are you attempting to delete the directory? Is there some specific error output from the deletion you can post?

**Comment by slawekwaga** [comment]
Apparently I can't replicate the problem... Wierd.
Was using rm -r on linux cli.
It spurted out input/output errors.
No logs. Sorry.

**Comment by Antidote** [comment]
that sounds like a hardware fault

**Comment by slawekwaga** [comment]
Most likely.
Closing for now.
