### ISSUE TITLE
[maybe] graphics correctly loading (incorrectly) for Subventilation Shaft Section A

### ISSUE THREAD

**Issue by tomlube** [AxioDL/urde#342]
In normal gameplay, if you beat the load to this room the graphics won't be loaded until you actually transition it, but it URDE they load no matter what - possibly related to instant load times but even in versions of dolphin/nintendont where instant load times were a problem you could usually still pull this off

**Comment by Antidote** [comment]
Definitely load time related especially if you're using an SSD with URDE, Dolphin has more overhead which slows down loading a fair bit in comparison.
