### ISSUE TITLE
Program Will Not Run

### ISSUE THREAD

**Issue by Pixel3r** [AxioDL/urde#357]
![image](https://user-images.githubusercontent.com/46037893/94091002-fb07c400-fdcb-11ea-884a-092677364d8a.png)
After having to manually download 3 .dll files, I got this error, and could not make further progress.

**Comment by Antidote** [comment]
You'll need to download the runtime for Windows 7, it should be available via windows update.

**Comment by encounter** [comment]
Delete the downloaded DLL files and use https://aka.ms/vs/16/release/vc_redist.x64.exe

**Comment by Pixel3r** [comment]
> 
> 
> Delete the downloaded DLL files and use https://aka.ms/vs/16/release/vc_redist.x64.exe

XInput1_4.dll is still missing

**Comment by encounter** [comment]
https://www.microsoft.com/en-us/download/details.aspx?id=35
