### ISSUE TITLE
[D3D11] Cannot run MP1 after CModelShaders commit

### ISSUE THREAD

**Issue by SirMangler** [AxioDL/urde#363]
It would seem since this commit: https://github.com/AxioDL/urde/commit/168eb6ac3989fe8e3aa153b1879895bcf48d5a37 I cannot run MP1 with **D3D11** without a `Boo HLSL Source(352,21-37): error X3004: undeclared identifier 'LightingFunc'` error during shader compilation.

I am compiling on Windows 10 with x64-MSVC, Visual Studio 2019 16.8.3 (latest at the time of writing this).

![image](https://user-images.githubusercontent.com/4237834/103445598-528cba00-4c6e-11eb-8b46-07a28e2db035.png)
Full log: https://hastebin.com/ewileconar.log

**Comment by encounter** [comment]
Fixed in https://github.com/AxioDL/urde/commit/5191534841eaa5249b70fd9b06c5758d362ddc2f
